In [1]:
"""(1) Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

OUTPUT:
Original array: [  1   7  13 105]
Size of the memory occupied by the said array: 16 bytes
"""
import numpy as np

mat = np.array([1, 7, 13, 105], dtype = np.uint16)
print(mat)


[  1   7  13 105]


In [2]:
"""(2)  Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

OUTPUT:
An array of 10 zeros:
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
An array of 10 ones:
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
An array of 10 fives:
[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]     
"""
mat = np.zeros(10)
print(mat)
mat = np.ones(10)
print(mat)
nat = np.ones(10) * 5
print(mat)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
"""(3) Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

OUTPUT:
15 random numbers from a standard normal distribution:
[ 0.53846169  2.09449415  2.01629186 -0.3256968  -0.01330516  1.12115378
  0.69266383 -1.09772731 -2.29868014  1.68440454 -0.47930023  0.85485553
 -1.16137237 -0.5739729  -1.06949766]
"""

mat = np.random.normal(loc=0, scale=1, size=15)
mat


array([ 0.07161247,  0.36817321,  0.39929356,  0.85874997, -0.17992893,
        1.25214188,  0.29121197, -0.04747594, -0.80767393,  1.19162249,
       -1.58224808, -1.49839142,  1.05886656,  0.50169751, -0.62162342])

In [8]:
"""(4) Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.

OUTPUT:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
"""
mat = np.arange(10, 22).reshape(3, 4)
mat


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [14]:
"""(5) Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

OUTPUT:
Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]
"""

mat = np.random.randint(0, 16, size=(4, 4))
print(f"original mat is \n{mat}")
mat[[0,-1],:]=mat[[-1,0],:]
print(f"array after change is \n{mat}")


original mat is 
[[12 13  6  8]
 [14 13  1 12]
 [10  1  9  9]
 [ 3  4  0 10]]
array after change is 
[[ 3  4  0 10]
 [14 13  1 12]
 [10  1  9  9]
 [12 13  6  8]]


In [21]:
"""(6) Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.

OUTPUT:
Original array:
[[5.54 3.38 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]

Elements of the said array greater than 5
[5.54 7.99 6.99 9.29]

Elements of the said array less than 6
[5.54 3.38 3.54 4.38 1.54 2.39]
"""

mat = np.array([[5.54, 3.38, 7.99],
                [3.54, 4.38, 6.99],
                [1.54, 2.39, 9.29]])
list_ = []
for row in mat:
    list_.extend(col for col in row if col > 5)
list_
  

array([5.54, 7.99, 6.99, 9.29])

In [27]:
"""(7) Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

OUTPUT:
Original array:
[[10 40]
 [30 20]]
Sort the array along the first axis:
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]
"""

mat = np.array([[10, 40],
                [30, 20]])
print(f"original array is \n{mat}\n")
mat = np.sort(mat, axis=0)
print(f"array after sort, with axis = 0, is\n{mat}\n")
mat = np.sort(mat, axis=1)
print(f"array after sort, with axis = 1, is\n{mat}\n")
mat = np.sort(mat, axis=None)
print(f"array after sort, with axis = None, is\n{mat}\n")




original array is 
[[10 40]
 [30 20]]

array after sort, with axis = 0, is
[[10 20]
 [30 40]]

array after sort, with axis = 1, is
[[10 20]
 [30 40]]

array after sort, with axis = None, is
[10 20 30 40]



In [28]:
"""(8) Write a NumPy program to sort an given array by the n-th column.

OUTPUT:
Original array:

[[26 45 40]
 [39 19 41]
 [29 19 14]]

Sort the said array by the nth column: 
[[39 19 41]
 [29 19 14]
 [26 45 40]]
"""

mat = np.array([[26, 45, 40],
                [39, 19, 41],
                [29, 19, 14]])
print(f"original array is\n{mat}\n")
mat = mat[mat[:,1].argsort()]
print(f"array after sort \n{mat}\n")




original array is
[[26 45 40]
 [39 19 41]
 [29 19 14]]

array after sort 
[[39 19 41]
 [29 19 14]
 [26 45 40]]

